name: Deploy to Server

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+" # Matches tags like 1.0.0, 2.1.3, etc.

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the project
        run: |
          node build.js --production

      - name: Deploy to Server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SERVER_DEPLOY_PATH: ${{ secrets.SERVER_DEPLOY_PATH }}
          # Email secrets
          CONTACT_EMAIL_TO: ${{ secrets.CONTACT_EMAIL_TO }}
          GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          # reCAPTCHA secrets
          RECAPTCHA_SITE_KEY: ${{ secrets.RECAPTCHA_SITE_KEY }}
          RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}
          # GTM
          GTM_CONTAINER_ID: ${{ secrets.GTM_CONTAINER_ID }}
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "$SERVER_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts

          # Create deployment directory if it doesn't exist
          ssh $SERVER_USER@$SERVER_HOST "mkdir -p $SERVER_DEPLOY_PATH"

          # Replace placeholders in HTML files before deployment
          sed -i "s/YOUR-RECAPTCHA-SITE-KEY/$RECAPTCHA_SITE_KEY/g" web/index.html
          sed -i "s/GTM-XXXXXXX/$GTM_CONTAINER_ID/g" web/index.html web/privacy.html

          # Deploy website files from web folder
          rsync -avz --delete \
            --exclude '.git' \
            --exclude '.github' \
            --exclude 'node_modules' \
            --exclude '*.md' \
            --exclude '.gitignore' \
            --exclude '.DS_Store' \
            --exclude 'config.php' \
            --exclude 'vendor' \
            --exclude '.env' \
            web/ \
            $SERVER_USER@$SERVER_HOST:$SERVER_DEPLOY_PATH/

          # Create config.php from example with secrets
          ssh $SERVER_USER@$SERVER_HOST "cd $SERVER_DEPLOY_PATH && cp config.example.php config.php"
          
          # Create .env file with secrets on server
          ssh $SERVER_USER@$SERVER_HOST "cat > $SERVER_DEPLOY_PATH/.env << 'EOF'
CONTACT_EMAIL_TO=$CONTACT_EMAIL_TO
GMAIL_USERNAME=$GMAIL_USERNAME
GMAIL_APP_PASSWORD=$GMAIL_APP_PASSWORD
RECAPTCHA_SITE_KEY=$RECAPTCHA_SITE_KEY
RECAPTCHA_SECRET_KEY=$RECAPTCHA_SECRET_KEY
EOF"

          # Run composer install on server
          ssh $SERVER_USER@$SERVER_HOST "cd $SERVER_DEPLOY_PATH && composer install --no-dev --optimize-autoloader"

          # Set proper permissions
          ssh $SERVER_USER@$SERVER_HOST "find $SERVER_DEPLOY_PATH -type f -exec chmod 644 {} \;"
          ssh $SERVER_USER@$SERVER_HOST "find $SERVER_DEPLOY_PATH -type d -exec chmod 755 {} \;"
          ssh $SERVER_USER@$SERVER_HOST "chmod 600 $SERVER_DEPLOY_PATH/config.php $SERVER_DEPLOY_PATH/.env"
          ssh $SERVER_USER@$SERVER_HOST "chmod 755 $SERVER_DEPLOY_PATH/send-email-smtp.php"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            ## Currency Converter v${{ github.ref_name }}

            ### What's New
            Please see the commit history for changes.
            
            ### Installation
            - **Chrome**: Visit the Chrome Web Store (coming soon)
            - **Firefox**: Visit addons.mozilla.org (coming soon)
            
            For development/testing, use the full release workflow with 'v' prefix tags.