name: Deploy to Linode

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'  # Matches tags like 1.0.0, 2.1.3, etc.

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Build the project
      run: |
        node build.js
    
    - name: Deploy to Linode
      env:
        LINODE_HOST: ${{ secrets.LINODE_HOST }}
        LINODE_USER: ${{ secrets.LINODE_USER }}
        LINODE_SSH_KEY: ${{ secrets.LINODE_SSH_KEY }}
        LINODE_DEPLOY_PATH: ${{ secrets.LINODE_DEPLOY_PATH }}
      run: |
        # Setup SSH
        mkdir -p ~/.ssh
        echo "$LINODE_SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $LINODE_HOST >> ~/.ssh/known_hosts
        
        # Create deployment directory if it doesn't exist
        ssh $LINODE_USER@$LINODE_HOST "mkdir -p $LINODE_DEPLOY_PATH"
        
        # Copy website files
        rsync -avz --delete \
          --exclude '.git' \
          --exclude '.github' \
          --exclude 'node_modules' \
          --exclude '*.md' \
          --exclude '.gitignore' \
          --exclude 'build.sh' \
          --exclude 'cc/' \
          --exclude 'chrome/' \
          --exclude 'firefox/' \
          index.html privacy.html \
          $LINODE_USER@$LINODE_HOST:$LINODE_DEPLOY_PATH/
        
        # Optional: Copy built extensions to a downloads directory
        ssh $LINODE_USER@$LINODE_HOST "mkdir -p $LINODE_DEPLOY_PATH/downloads"
        
        # Create zip files for extensions
        cd chrome && zip -r ../chrome-extension.zip . && cd ..
        cd firefox && zip -r ../firefox-extension.zip . && cd ..
        
        # Upload extension zips
        rsync -avz chrome-extension.zip firefox-extension.zip \
          $LINODE_USER@$LINODE_HOST:$LINODE_DEPLOY_PATH/downloads/
        
        # Optional: Set proper permissions
        ssh $LINODE_USER@$LINODE_HOST "find $LINODE_DEPLOY_PATH -type f -exec chmod 644 {} \;"
        ssh $LINODE_USER@$LINODE_HOST "find $LINODE_DEPLOY_PATH -type d -exec chmod 755 {} \;"
    
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        body: |
          ## Universal Currency Converter v${{ github.ref_name }}
          
          ### Downloads
          - [Chrome Extension](https://${{ secrets.LINODE_HOST }}/downloads/chrome-extension.zip)
          - [Firefox Extension](https://${{ secrets.LINODE_HOST }}/downloads/firefox-extension.zip)
          
          ### What's New
          Please see the commit history for changes.