name: Deploy to Server

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+" # Matches tags like 1.0.0, 2.1.3, etc.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the project
        run: |
          node build.js

      - name: Deploy to Server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SERVER_DEPLOY_PATH: ${{ secrets.SERVER_DEPLOY_PATH }}
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "$SERVER_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts

          # Create deployment directory if it doesn't exist
          ssh $SERVER_USER@$SERVER_HOST "mkdir -p $SERVER_DEPLOY_PATH"

          # Deploy website files from web folder
          rsync -avz --delete \
            --exclude '.git' \
            --exclude '.github' \
            --exclude 'node_modules' \
            --exclude '*.md' \
            --exclude '.gitignore' \
            --exclude '.DS_Store' \
            web/ \
            $SERVER_USER@$SERVER_HOST:$SERVER_DEPLOY_PATH/

          # Set proper permissions
          ssh $SERVER_USER@$SERVER_HOST "find $SERVER_DEPLOY_PATH -type f -exec chmod 644 {} \;"
          ssh $SERVER_USER@$SERVER_HOST "find $SERVER_DEPLOY_PATH -type d -exec chmod 755 {} \;"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: |
            ## Currency Converter v${{ github.ref_name }}

            ### What's New
            Please see the commit history for changes.
            
            ### Installation
            - **Chrome**: Visit the Chrome Web Store (coming soon)
            - **Firefox**: Visit addons.mozilla.org (coming soon)
            
            For development/testing, use the full release workflow with 'v' prefix tags.